# Numpy

Numerisk python
- Arrays (fält)
- Lik listor 
- Matematiska operationer på Arrays
- Modelerande vektorer och matriser

In [1]:
import numpy as np

array1 = np.array([1,2,3,4])

lista1 = [1,2,3,4]

print(f"Array: {array1}")
print(f"Lista: {lista1}")

# Indexera arrays, fungerar på samma set som att indexera listor []
print(array1[2])

# Multiplicera alla tal med 2
array2 = array1*2
print(array2)

lista2 = lista1*2
print(lista2)

kvadrater = array1**2
print(kvadrater)


Array: [1 2 3 4]
Lista: [1, 2, 3, 4]
3
[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]
[ 1  4  9 16]


## Användbara numpy+funktioner
- zeros
- ones 
- arange
- linspace
- matematiska fun ktioner och konstruktioner: pi, sqrt

In [15]:
import numpy as np
import math

# arange
tal = np.arange(10)
print(tal)
print(np.sqrt(tal))

nollor = np.zeros(6)
print(nollor)

ettor = np.ones(6)
print(ettor)



[0 1 2 3 4 5 6 7 8 9]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]


### Simulera tärningskast

In [5]:
import numpy as np 
import random as rnd

# arrays med nollor för att parealloikera minne
utfall = np.zeros(6, dtype=int)
print(utfall)

antal_kast = 10000
for i in range(antal_kast):
    kast = rnd.randint(1,6)
    utfall[kast-1] += 1

print(f"Tärningskasy: {utfall}")
print(f"Snnorlikhet: {utfall/antal_kast}")



[0 0 0 0 0 0]
Tärningskasy: [1588 1703 1685 1728 1672 1624]
Snnorlikhet: [0.1588 0.1703 0.1685 0.1728 0.1672 0.1624]
